### ISSUE TITLE
Error Downloading - Cannot parse URL. Unable to download repository if the url starts with https://

### ISSUE THREAD

**Issue by rdebourbon** [camicri/cube-get#15]
I added the docker ubuntu repository to my apt-sources - but now cannot download repositories using the windows client. I get an error downloading where it is unable to parse the URL.

I was following this guide:
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04

And added the repo using this:
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

**Comment by camicri** [comment]
Hi ray, thank you for creating an issue.

I reviewed the code and it has indeed limitation on https repositories. Sorry for that.
I will tag this issue as bug and fix it.

**Comment by camicri** [comment]
Hi @rdebourbon , I have released a patch to fix this issue.
You can download updated cube-get for Linux and Windows [here](https://github.com/camicri/cube-get/releases/tag/4.3.1-1.3).

Let me know if you still encounter the issue.
