### ISSUE TITLE
Cube-get showing zero packages available (Ubuntu 20.04)

### ISSUE THREAD

**Issue by mhodgkins1** [camicri/cube-get#18]
I installed cube-get 4.3-1.3 on a clean install of Ubuntu 20.04 (offline) and Windows 7 (has internet connection)
I successfully created my project on Ubuntu but under * menu shows no packages available ("Available 0")
Also zero for everything else except "Installed" which shows 1,613

See image below, which also shows messages in the terminal on startup

![CubeRun](https://user-images.githubusercontent.com/55936400/92103010-54f31a80-ee1a-11ea-8c04-5904fb96676e.jpg)

I see no error messages but do the [WebSocket] lines with repository-scan-progress look correct? 

Further information ...

info.cube is
#CubeGet Project Information File
Architecture : binary-amd64
Distribution : Ubuntu
Project Version : 2
Operating System : Ubuntu 20.04 LTS
Date Created : 09/02/20 20:40:26
Computer Name : mick
Release : 20.04
Project Name : seasprite
Code Name : focal

There are files in the projects data/list folder as follows that seem to contain package lists e.g.
archive.ubuntu.com_ubuntu_dists_focal_main_binary-amd64_Packages
archive.ubuntu.com_ubuntu_dists_focal_restricted_binary-amd64_Packages
Ubuntu%2020.04%20LTS%20%5fFocal%20Fossa%5f%20-%20Release%20amd64%20(20200423)_dists_focal_main_binary-amd64_Packages
Ubuntu%2020.04%20LTS%20%5fFocal%20Fossa%5f%20-%20Release%20amd64%20(20200423)_dists_focal_restricted_binary-amd64_Packages
...etc.

Any idea how I could troubleshoot this?

**Comment by camicri** [comment]
Hi @mhodgkins1, thanks for creating an issue.

When you created the project on Ubuntu, does it show zero Available packages as well? Or only on Windows?
There must be an issue on `sources.list` file. This file has the list of repositories to check.

The file would contain lines like this (First 6 lines)
https://gist.github.com/ishad0w/788555191c7037e249a439542c53e170

Could you share the contents of the said file? It is located on below path
 `cube-get/projects/seasprite/data/sources/sources.list`

Also, you can change the downloader on Cube Settings if there is an issue with the downloader (Currently set to Axel).
If you can share the whole project folder to me that would be really helpful as well.

**Comment by mhodgkins1** [comment]
Hi camcicri,
Thanks for the response. 

The project shows zero Available packages also on the Ubuntu machine when I created it.

My project folder has only the seasprite project in it. I've zipped that and attached it.

[seasprite.zip](https://github.com/camicri/cube-get/files/5172319/seasprite.zip)

I tried modifying my sources.list file to be exactly as the one you linked and that helped a bit. When I did that and created a new project I could see 6,227 Available packages. This is a step forward but this doesn't seem to be complete as I was expecting about 55,000. For example, trying to follow your tutorial, I found that vlc is not one of the available packages listed.

I was able to mark for download and then download "build-essentials" so maybe the downloader settings are ok?

Thanks for your help with this,

M

**Comment by camicri** [comment]
Hi again, @mhodgkins1  that was a fast reply.

I noticed that on your `sources.list`, you are using `jp` mirror for the repositories:
`deb http://jp.archive.ubuntu.com/ubuntu/ focal universe`

Could you try changing it to below and check if the available packages will increase? Or all `jp` occurrence. Save the file and reload the repository afterwards.
`deb http://archive.ubuntu.com/ubuntu/ focal universe`

This might be a limitation on our side if it works (Mirrored repository). Sorry for the inconvenience.

**Comment by camicri** [comment]
Additional info:
`vlc` is not listed I think because it belongs to the `universe` repository. I see that only `main` and `restricted` are correct in your package list.

If you check the `data/lists` folder of your project, below filename is invalid:
`Ubuntu%2020.04%20LTS%20%5fFocal%20Fossa%5f%20-%20Release%20amd64%20(20200423)_dists_focal_main_binary-amd64_Packages`
It should be this:
`archive.ubuntu.com_ubuntu_dists_focal_main_binary-amd64_Packages`

If you rename these manually and reload the repository, you should get additional packages. I'm not sure what is going on currently on app but I'll recheck this.

**Comment by mhodgkins1** [comment]
Thanks for the help. I've made some progress. I've done the following:

1. Deleted the jp. text so I'm not using the japanese archives. When I did this, I could then see about 6,000 available packages.
2. As you pointed out, I didn't have package lists in my data/lists folder for universe and multiverse so that's why I got less than expected and no vlc. So I moved the project to the Windows machine, loaded it and did Repository->Download Repositories. The package lists appeared as .gz files in the data/list/temp folder but still only 6,000 Available packages showing.
3. I unzipped the .gz files and manually moved them all to the data/list folder replacing what was in there. Then restarted Cube-get and I see 60,991 Available packages - Hooray!

Is the last step supposed to be manual or is the software supposed to do that unzip and move?

By the way, the strange package list names I had seemed to come from the name of the installation CD. 

Anyway, all seems to be working now and I can see vlc is also present.

Thanks for your help. This software is a great solution to my problem. I couldn't build the drivers for my usb wifi adapter because make was not installed in the default install. Now I hope I can fix that!

From my point of view my problem is now solved.

**Comment by camicri** [comment]
Hi @mhodgkins1, glad to hear that the available packages are now showing correctly 🎉 

>Is the last step supposed to be manual or is the software supposed to do that unzip and move?

For the `.gz` on `data/list/temp` folder, ideally it should be decompressed by the app automatically. I was really impressed that you figured that out 😮. 
It seems that the `gzip.exe`, the app used to decompresss that, is not working (It is located at `cube-get\cube-system\bin` I think.

Sorry for the inconvenience here, I'll recheck this and provide a fix.
Feel free to message again if you need more help.
